[custom]
enable_rule_generator=true
overwrite_original_rules=false
clash_rule_base=https://raw.githubusercontent.com/b1ghawk119/subconverter/main/base/clash.tpl?t=175461352

ruleset=🎯 全球直连,https://raw.githubusercontent.com/b1ghawk119/ACL4SSR/master/Clash/Misc.za.list?t=1723921961
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=💬 AI,https://raw.githubusercontent.com/b1ghawk119/ACL4SSR/master/Clash/Ruleset/AI.list?t=1750174014
;ruleset=💬 Poe,https://raw.githubusercontent.com/b1ghawk119/ACL4SSR/master/Clash/Ruleset/Poe.list
;ruleset=💬 区块链网络,https://raw.githubusercontent.com/b1ghawk119/ACL4SSR/master/Clash/Coin.list
ruleset=💬 杂项,https://raw.githubusercontent.com/b1ghawk119/ACL4SSR/master/Clash/Misc.list?t=175392064
ruleset=📲 电报信息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/b1ghawk119/ACL4SSR/master/Clash/Custom.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]🔯 故障转移`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=🔯 故障转移`fallback`.*`http://www.gstatic.com/generate_204`180
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🕞 AI测速`url-test`!!GROUPID=!0`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🕞 AI测速`url-test`!!GROUPID=!0`https://chatgpt.com/`300,,50
;custom_proxy_group=💬 AI`select`[]🕞 AI测速`[]🚀 节点选择`[]🎯 全球直连`[]🔯 故障转移`[]♻️ 自动选择`!!GROUPID=!0
;custom_proxy_group=💬 AI`select`[]🚀 节点选择`[]🎯 全球直连`[]🔯 故障转移`[]♻️ 自动选择`!!GROUPID=!0
custom_proxy_group=💬 AI`select`[]🚀 节点选择`[]🎯 全球直连`[]🔯 故障转移`[]♻️ 自动选择`.*
;custom_proxy_group=💬 Poe`select`[]🚀 节点选择`[]🎯 全球直连`[]🔯 故障转移`[]♻️ 自动选择`!!GROUPID=!0
;custom_proxy_group=💬 区块链网络`select`[]🚀 节点选择`[]🎯 全球直连`[]🔯 故障转移`[]♻️ 自动选择`!!GROUPID=!0
;custom_proxy_group=💬 杂项`select`[]🚀 节点选择`[]🎯 全球直连`[]🔯 故障转移`[]♻️ 自动选择`!!GROUPID=!0
custom_proxy_group=💬 杂项`select`[]🚀 节点选择`[]🎯 全球直连`[]🔯 故障转移`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=📲 电报信息`select`[]🚀 节点选择`[]🎯 全球直连`[]🔯 故障转移`[]♻️ 自动选择`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🔯 故障转移`[]♻️ 自动选择
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连`[]🔯 故障转移`[]♻️ 自动选择`.*


;exclude_remarks=(到期|关注|电报群|TG群|tg群|群号|电报|进群|失效|失联|距离|润发|剩余流量|时间|官网|产品|平台|机场|订阅|联系|微信|频道|\p{Cc})

;rename=!!GROUP=yyjc!!^@[一元机场]
;rename=!!GROUP=xjbjc!!^@[性价比]
;rename=!!GROUP=fxxjc!!^@[风萧萧]
;rename=!!GROUP=bkmjc!!^@[宝可梦]
;rename=!!GROUP=yjxl_a!!^@[应急A]
;rename=!!GROUP=yjxl_b!!^@[应急B]
;rename=!!GROUP=yjxl_c!!^@[应急C]
